# Generated by Django 3.1.1 on 2020-09-06 07:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200906_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='age_limit',
            field=models.IntegerField(blank=True, choices=[(3, 3), (7, 7), (13, 13), (16, 16), (18, 18)], null=True, validators=[django.core.validators.MaxValueValidator(18), django.core.validators.MinValueValidator(0)]),
        ),
    ]
