# Generated by Django 3.1.1 on 2020-09-12 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200906_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('country',)},
        ),
        migrations.AlterField(
            model_name='genre',
            name='age_limit',
            field=models.IntegerField(blank=True, choices=[(0, 'kids'), (1, 'teens'), (2, 'adults')], null=True, validators=[django.core.validators.MaxValueValidator(18), django.core.validators.MinValueValidator(0)]),
        ),
    ]
