# Generated by Django 3.1.1 on 2020-09-13 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200912_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['released']},
        ),
    ]
